[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Sagittal Brain"
version = "1.0.0"
dependencies = ["numpy",
]

[tool.hatch.build.targets.wheel]
packages = [
  "src/sagittal_brain",
]
